### ISSUE TITLE
How to develop as a chrome extension?

### ISSUE THREAD

**Issue by tivac** [amitnovick/xstate-devtools#12]
Very excited to get this up & running, so spent some time digging around as part of my looking into #10. I forked the repo, fought a bit with the deps to get everything install correctly, and then ran `npm run develop`.

Everything compiled and started watching correctly, and it spat out http://localhost:3000.

Opening the resulting URL in Chrome showed a bunch of errors that looked like the page was expecting to be run as a chrome extension?

I did some searching but... I don't know how to do that, could the README please be fleshed out a bit further with the next steps for developing after running `npm run develop`?

**Comment by amitnovick** [comment]
Yea sorry about that, the instructions for developing this were lacking a bit.

The setup is quite involved, since browser extension development is a little different from normal web app development (many gotcha's and esoteric things to learn about in order to not tumble over).

I have made some progress on it with https://github.com/amitnovick/xstate-devtools/commit/884f6347c9c1903415e606d4d4e437c9349c406c

The thing is that you're not supposed to be accessing the URL in a browser at all, since browser extension APIs are being used. Instead, the app should be accessed through the DevTools panel, and I suggest following the instructions for smoothest experience.
