### ISSUE TITLE
Nothing is rendered

### ISSUE THREAD

**Issue by CodingDive** [amitnovick/xstate-devtools#13]
Hey, thank you for taking on adding devtools. Very excited about this project 😍 

I just installed the extension on chrome and tried my local app as well as the sandbox. It seems that nothing is rendered to the extension.

![image](https://user-images.githubusercontent.com/28842311/70006078-1f0fc580-156c-11ea-9a7f-0609c620d4ca.png)

# Versions
```
XState: 4.7.1
Chrome: 78.0.3904.108
Windows: 10 OS Version 1809 (Build 17763.864)
```

Let me know if you need more information.

**Comment by amitnovick** [comment]
Hi @CodingDive, thank you for reporting the issue.

For starters, could you verify passsing `devTools: true` in interpreter options?

That would be:
`interpret(machine, { devTools: true })` with `interpret` from xstate
or `useMachine(machine, { devTools: true })` with `useMachine` from @xstate/react

(I should implement a screen for the UI that would remind you to do that, instead of showing blank page)

I also added these instructions to the `README` just now with https://github.com/amitnovick/xstate-devtools/commit/3096138295fa9633c431ebf8342e71026fea70b6

**Comment by amitnovick** [comment]
If you are passing the devtools option already, it would help a ton if you could try doing the following:
- Share the machine config code
- (optional) When the blank screen appears, you could open a devtools inspection window for it using Ctrl+Shift+I, and if there might be an error/warning in the console there, please report that.

Getting user feedback and solving arising issues is really important because testing is super hard inside a web extension. I'm considering implementing a Toast notification which would trigger on encountering an error, and include the stacktrace to make it easier to understand what's going on and easy to report.

**Comment by CodingDive** [comment]
Thank you for your quick reply.
Trying it on a page that has ~10 active machines renders the blank box (defined `devTools: true` on a few of them to try).

A page with one active machine just shows "Resetting..."  

Can't share the machines at the moment. If I had to guess, its probably because I'm using TypeScript and all my state nodes + events are enum constants.

On the page that was has multiple machines running, I'm also heavily making use of Actors which I don't think are supported.

Unfortunately, I couldn't find anything in the log.

**Comment by RainerAtSpirit** [comment]
@CodingDive See if the following workaround works for you as well.

* in the source tab make sure the the devtools are loaded, if not press the XState DevTools button again until they show up.

![image](https://user-images.githubusercontent.com/581644/70327498-359d7180-1837-11ea-8c80-c357a17f8292.png)

* pressing Ctrl F5 should now render the xstate/viz

![image](https://user-images.githubusercontent.com/581644/70327557-5960b780-1837-11ea-81b4-78032f85d7e1.png)

As long as you have dev tools enabled on the parent machine all spawned actors will show up and you can switch between using the dropdown.

@amitnovick I suspect this is a timing issue, but couldn't nail it down by now.

**Comment by CodingDive** [comment]
@rainerAtSpirit I ensured that XState DevTools is loaded and running and that I'm passing `devTools: true` to the machines I want to inspect. It still shows nothing but `Resetting...` for me 😕

**Comment by RainerAtSpirit** [comment]
@CodingDive Here's another approach. Try setting a breakpoint at line 19 in `injected.js` and than press `Ctrl F5` a couple of times. Once the breakpoint is hit, you can remove it and switch to the XState Devtools tab.
![image](https://user-images.githubusercontent.com/581644/70453983-fd519980-1aa9-11ea-86a7-b15b1fc8c904.png)

**Comment by amitnovick** [comment]
@RainerAtSpirit
that looks like a useful debugging tip, good find!

@CodingDive
I would love to help, could you share a code reproduction of it? preferably a minimal one to help narrow it down.

**Comment by CodingDive** [comment]
@amitnovick is the extension supposed to work on Codesandbox? It's showing `Resetting...` for me when visiting https://codesandbox.io/s/beautiful-germain-hueum. The breakpoint seems to never get hit no matter how often I refresh. Haven't tried to run this particular example locally though.

**Comment by amitnovick** [comment]
> @amitnovick is the extension supposed to work on Codesandbox? It's showing `Resetting...` for me when visiting https://codesandbox.io/s/beautiful-germain-hueum. The breakpoint seems to never get hit no matter how often I refresh. Haven't tried to run this particular example locally though.

Yes, with the two caveats:
1. By default XState doesn't try to connect with devtools, so you have to pass `devTools: true`in the options arg with `useMachine` (or `interpret` for that matter)
2. There's an issue with CodeSandbox where the extension is unusable in the editor page, and would only work when opened in the new window setup. That's what I used to try out your code, which was working fine on my end:

![Screenshot_2019-12-12_00-23-40](https://user-images.githubusercontent.com/43674238/70666924-5e2ecc80-1c78-11ea-8fae-539f799d96a4.png)

Gonna put some time in later this week to get the CodeSandbox issue sorted out, feel free to open an issue so that you'll be able to track it better.

**Comment by amitnovick** [comment]
Now, is there any more to this issue? are you still stuck with "Resetting" screen on your local app? if so, I'll be able to help with that if you share the machine code that causes it.

**Comment by CodingDive** [comment]
Sorry. I had `devTools: true` before saving the codesandbox. Glad it worked
in the separate window. I'll open an issue about the Codesandbox editor
support.

Unfortunately, I can't replicate the issue. I just have tons of machines
with what feels to be every possible xstate feature. Deeply nested actors,
custom guards that are defined with string enums, deep state transitions by
#id, delayed transitions. I'm pretty sure that one of those things is not
fully supported by the visualizer yet but I can't seem to isolate it at the
moment.

Do you know why I don't get any logs from the devtools?

**Comment by CodingDive** [comment]
Ah actually. I just realized that I'm still on the old branch without
XState 4.7.. Will report back once I've fixed all my bugs and upgrade 😁😅

**Comment by CodingDive** [comment]
Sorry about that, I think this was on me for using the old version of XState. I'll reopen the issue should I run into the issue when using the new version. ✌️

**Comment by hanzlahabib** [comment]
My DevTool endup showing blank white page where it shows diagram res works fine
![image](https://user-images.githubusercontent.com/41893448/112315229-bf42ae00-8ccb-11eb-9712-c4c3e0bfd675.png)
any assistance will be appreciated 
Thanks
